Add extra steps to validate consistency of pods

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -143,8 +143,16 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-cocoapods-
 
+      - name: Validate Podfile.lock consistency
+        run: |
+          cd example/ios
+          if ! cmp -s Podfile.lock Pods/Manifest.lock; then
+            echo "Podfile.lock is out of sync, requiring pod install"
+            echo "pod_install_required=1" >> $GITHUB_ENV
+          fi
+
       - name: Install cocoapods
-        if: env.turbo_cache_hit != 1 && steps.cocoapods-cache.outputs.cache-hit != 'true'
+        if: env.turbo_cache_hit != 1 && (steps.cocoapods-cache.outputs.cache-hit != 'true' || env.pod_install_required == '1')
         run: |
           cd example/ios
           pod install
